
GET http://localhost:3000/movies

###
POST http://localhost:3000/movies
Content-Type: application/json

{
        "name": "The Matrix",
        "year": 1999,
        "sinopsis": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers."
}

###
DELETE http://localhost:3000/movies/6

###

GET http://localhost:3000/movies/2